import re
regex = re.compile('Python|Automação')
mo = regex.search('Curso de Python do Zero a Automação')
print(mo.group())
mo = regex.search('Curso de Automação')
print(mo.group())
emails = re.compile('jose@(gmail.com|yahoo.com|outlook.com|hotmail.com|apple.com)')
mo = emails.search('Enviando email para jose@yahoo.com')
print(mo.group())
print(mo.group(1))
mo = emails.search('Enviando email para jose@gmail.com')
print(mo.group())
print(mo.group(1))
mo = emails.search('Enviando email para jose@outlook.com')
print(mo.group())
print(mo.group(1))
mo = emails.search('Enviando email para jose@hotmail.com')
print(mo.group())
print(mo.group(1))
mo = emails.search('Enviando email para jose@apple.com')
print(mo.group())
print(mo.group(1))
mo = emails.search('Enviando email para jose@fatec.sp.gov.com')
print(mo.group())
print(mo.group(1))